### ISSUE TITLE
Create a settings page in VS Options

### ISSUE THREAD

**Issue by rprouse** [rprouse/GitHubExtension#117]
In order to support configuration of the extension, I first need to support settings within the Visual Studio options dialog. This issue should be combined with one of the other issues that requires settings.

**Comment by sharwell** [comment]
Are you already familiar with how to do this? If not, let me know and I can help out with it.

**Comment by rprouse** [comment]
Thanks, I think I am good, I have Phil Haack's blog post on how to do it. If I run into problems, I will give you a shout.

http://haacked.com/archive/2014/07/30/visual-studios-extensions-settings/
