### ISSUE TITLE
Update to the new GitHub Authorizations API (breaking change) 

### ISSUE THREAD

**Issue by ptoomey3** [rprouse/GitHubExtension#119]
The [GitHub Authorizations API](https://developer.github.com/v3/oauth_authorizations/) will no longer return `token` for many APIs as of April 20, 2015. You can read more on the [developer blog](https://developer.github.com/changes/2015-02-20-migration-period-removing-authorizations-token/). The [login logic](https://github.com/rprouse/GitHubExtension/blob/8a1aa71a34f6efa780e49724d043584cf3421a2f/GitHubIssues/Model/GitHubApi.cs#L331) will need to be updated to use something more like https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app-and-fingerprint.

**Comment by ptoomey3** [comment]
The `fingerprint` value is not user visible, so you can use whatever metadata would be useful to distinguish between multiple unique installs of an application for a user. For example, you could use something like the SHA256 of a user's mac address to uniquely distinguish the authorization from the installation on a user's laptop from another on their desktop. So, if a particular install has lost track of the generated token (user deleted it, formatted their machine, etc) you can first delete the old authorization before creating a new one for the same machine.

**Comment by rprouse** [comment]
@ptoomey3, thanks for bringing this to my attention, I was not aware of the changes.

**Comment by rprouse** [comment]
http://haacked.com/archive/2014/04/24/octokit-oauth/

**Comment by rprouse** [comment]
Updated with a fingerprint using the latest version of Octokit
